development:
  adapter: postgresql
  database: myhelloword_dev

test: &TEST
  adapter: postgresql
  database: myhelloword_test
  min_messages: warning

production:
  adapter: postgresql
  database: myhelloword_prod